#' population des health regions selon ishaberry repository
#' @export

#

#   mutate(health_region = case_when(
#     health_region == "Gaspésie-Îles-de-la-Madeleine" ~ "Gaspésie",
#     health_region == "Abitibi-Témiscamingue" ~ "Abitibi",
#     health_region == "Terres-Cries-de-la-Baie-James" ~ "Terres-Cries",
#     TRUE ~ health_region)

# populations <-  readr::read_csv("https://raw.githubusercontent.com/ishaberry/Covid19Canada/master/other/hr_map.csv") %>%
#     mutate(pr_region = paste0(province,"-", health_region))
#
# prov_pop <- populations  %>% group_by(province) %>% summarise(pop = sum(pop))
#
# populations <- bind_rows(
#   populations,
#   prov_pop %>% filter(province== "Quebec") %>% mutate(health_region = "Ensemble du Québec", pr_region = "Quebec-Ensemble du Québec")
# )
# datapasta::dpasta(populations)
#



populations <- tibble::tribble(
                                          ~HR_UID,       ~province,                          ~health_region,    ~pop,                                      ~pr_region,
                                             4832,       "Alberta",                               "Calgary", 1680755,                               "Alberta-Calgary",
                                             4833,       "Alberta",                               "Central",  479601,                               "Alberta-Central",
                                             4834,       "Alberta",                              "Edmonton", 1443597,                              "Alberta-Edmonton",
                                             4835,       "Alberta",                                 "North",  460964,                                 "Alberta-North",
                                             4831,       "Alberta",                                 "South",  306399,                                 "Alberta-South",
                                              591,            "BC",                                "Fraser", 1902586,                                     "BC-Fraser",
                                              592,            "BC",                              "Interior",  805216,                                   "BC-Interior",
                                              593,            "BC",                                "Island",  846030,                                     "BC-Island",
                                              594,            "BC",                              "Northern",  298068,                                   "BC-Northern",
                                              595,            "BC",                     "Vancouver Coastal", 1219436,                          "BC-Vancouver Coastal",
                                             4603,      "Manitoba",                     "Interlake-Eastern",  133882,                    "Manitoba-Interlake-Eastern",
                                             4604,      "Manitoba",                              "Northern",   75783,                             "Manitoba-Northern",
                                             4602,      "Manitoba",                      "Prairie Mountain",  171368,                     "Manitoba-Prairie Mountain",
                                             4605,      "Manitoba",                       "Southern Health",  208018,                      "Manitoba-Southern Health",
                                             4601,      "Manitoba",                              "Winnipeg",  780414,                             "Manitoba-Winnipeg",
                                             1301, "New Brunswick",                 "Zone 1 (Moncton area)",  222694,           "New Brunswick-Zone 1 (Moncton area)",
                                             1302, "New Brunswick",              "Zone 2 (Saint John area)",  176280,        "New Brunswick-Zone 2 (Saint John area)",
                                             1303, "New Brunswick",             "Zone 3 (Fredericton area)",  183421,       "New Brunswick-Zone 3 (Fredericton area)",
                                             1304, "New Brunswick",              "Zone 4 (Edmundston area)",   48254,        "New Brunswick-Zone 4 (Edmundston area)",
                                             1305, "New Brunswick",             "Zone 5 (Campbellton area)",   25199,       "New Brunswick-Zone 5 (Campbellton area)",
                                             1306, "New Brunswick",                "Zone 6 (Bathurst area)",   76763,          "New Brunswick-Zone 6 (Bathurst area)",
                                             1307, "New Brunswick",               "Zone 7 (Miramichi area)",   44216,         "New Brunswick-Zone 7 (Miramichi area)",
                                             1012,            "NL",                               "Central",   91201,                                    "NL-Central",
                                             1011,            "NL",                               "Eastern",  317664,                                    "NL-Eastern",
                                             1014,            "NL",                     "Labrador-Grenfell",   36069,                          "NL-Labrador-Grenfell",
                                             1013,            "NL",                               "Western",   76608,                                    "NL-Western",
                                             1201,   "Nova Scotia",                      "Zone 1 - Western",  199165,                  "Nova Scotia-Zone 1 - Western",
                                             1202,   "Nova Scotia",                     "Zone 2 - Northern",  148470,                 "Nova Scotia-Zone 2 - Northern",
                                             1203,   "Nova Scotia",                      "Zone 3 - Eastern",  162088,                  "Nova Scotia-Zone 3 - Eastern",
                                             1204,   "Nova Scotia",                      "Zone 4 - Central",  461672,                  "Nova Scotia-Zone 4 - Central",
                                             6201,       "Nunavut",                               "Nunavut",   38780,                               "Nunavut-Nunavut",
                                             6101,           "NWT",                                   "NWT",   44826,                                       "NWT-NWT",
                                             3526,       "Ontario",                                "Algoma",  117036,                                "Ontario-Algoma",
                                             3527,       "Ontario",                                 "Brant",  151034,                                 "Ontario-Brant",
                                             3540,       "Ontario",                          "Chatham-Kent",  106091,                          "Ontario-Chatham-Kent",
                                             3530,       "Ontario",                                "Durham",  697355,                                "Ontario-Durham",
                                             3558,       "Ontario",                               "Eastern",  213064,                               "Ontario-Eastern",
                                             3533,       "Ontario",                            "Grey Bruce",  173372,                            "Ontario-Grey Bruce",
                                             3534,       "Ontario",                     "Haldimand-Norfolk",  119146,                     "Ontario-Haldimand-Norfolk",
                                             3535,       "Ontario",         "Haliburton Kawartha Pineridge",  189982,         "Ontario-Haliburton Kawartha Pineridge",
                                             3536,       "Ontario",                                "Halton",  596363,                                "Ontario-Halton",
                                             3537,       "Ontario",                              "Hamilton",  574263,                              "Ontario-Hamilton",
                                             3538,       "Ontario",                "Hastings Prince Edward",  170793,                "Ontario-Hastings Prince Edward",
                                             3539,       "Ontario",                           "Huron Perth",  144801,                           "Ontario-Huron Perth",
                                             3541,       "Ontario", "Kingston Frontenac Lennox & Addington",  208613, "Ontario-Kingston Frontenac Lennox & Addington",
                                             3542,       "Ontario",                               "Lambton",  132243,                               "Ontario-Lambton",
                                             3543,       "Ontario",            "Leeds Grenville and Lanark",  177605,            "Ontario-Leeds Grenville and Lanark",
                                             3544,       "Ontario",                      "Middlesex-London",  506008,                      "Ontario-Middlesex-London",
                                             3546,       "Ontario",                               "Niagara",  479183,                               "Ontario-Niagara",
                                             3547,       "Ontario",                 "North Bay Parry Sound",  129642,                 "Ontario-North Bay Parry Sound",
                                             3549,       "Ontario",                          "Northwestern",   81472,                          "Ontario-Northwestern",
                                             3551,       "Ontario",                                "Ottawa", 1028514,                                "Ontario-Ottawa",
                                             3553,       "Ontario",                                  "Peel", 1542001,                                  "Ontario-Peel",
                                             3555,       "Ontario",                          "Peterborough",  147908,                          "Ontario-Peterborough",
                                             3556,       "Ontario",                             "Porcupine",   85422,                             "Ontario-Porcupine",
                                             3557,       "Ontario",                               "Renfrew",  107955,                               "Ontario-Renfrew",
                                             3560,       "Ontario",                        "Simcoe Muskoka",  594494,                        "Ontario-Simcoe Muskoka",
                                             3575,       "Ontario",                          "Southwestern",  215401,                          "Ontario-Southwestern",
                                             3561,       "Ontario",                               "Sudbury",  204640,                               "Ontario-Sudbury",
                                             3562,       "Ontario",                           "Thunder Bay",  158165,                           "Ontario-Thunder Bay",
                                             3563,       "Ontario",                           "Timiskaming",   33800,                           "Ontario-Timiskaming",
                                             3595,       "Ontario",                               "Toronto", 2965712,                               "Ontario-Toronto",
                                             3565,       "Ontario",                              "Waterloo",  595465,                              "Ontario-Waterloo",
                                             3566,       "Ontario",            "Wellington Dufferin Guelph",  308963,            "Ontario-Wellington Dufferin Guelph",
                                             3568,       "Ontario",                         "Windsor-Essex",  428556,                         "Ontario-Windsor-Essex",
                                             3570,       "Ontario",                                  "York", 1181485,                                  "Ontario-York",
                                             1100,           "PEI",                  "Prince Edward Island",  156947,                      "PEI-Prince Edward Island",
                                             2408,        "Quebec",                 "Abitibi-Témiscamingue",  147542,                  "Quebec-Abitibi-Témiscamingue",
                                             2401,        "Quebec",                     "Bas-Saint-Laurent",  197322,                      "Quebec-Bas-Saint-Laurent",
                                             2403,        "Quebec",                    "Capitale-Nationale",  750645,                     "Quebec-Capitale-Nationale",
                                             2412,        "Quebec",                  "Chaudière-Appalaches",  428618,                   "Quebec-Chaudière-Appalaches",
                                             2409,        "Quebec",                             "Côte-Nord",   90704,                              "Quebec-Côte-Nord",
                                             2405,        "Quebec",                                "Estrie",  489479,                                 "Quebec-Estrie",
                                             2411,        "Quebec",         "Gaspésie-Îles-de-la-Madeleine",   90334,          "Quebec-Gaspésie-Îles-de-la-Madeleine",
                                             2414,        "Quebec",                            "Lanaudière",  515448,                             "Quebec-Lanaudière",
                                             2415,        "Quebec",                           "Laurentides",  620264,                            "Quebec-Laurentides",
                                             2413,        "Quebec",                                 "Laval",  438973,                                  "Quebec-Laval",
                                             2404,        "Quebec",                              "Mauricie",  520285,                               "Quebec-Mauricie",
                                             2416,        "Quebec",                            "Montérégie", 1421586,                             "Quebec-Montérégie",
                                             2406,        "Quebec",                              "Montréal", 2052910,                               "Quebec-Montréal",
                                             2410,        "Quebec",                        "Nord-du-Québec",   13633,                         "Quebec-Nord-du-Québec",
                                             2417,        "Quebec",                               "Nunavik",   14102,                                "Quebec-Nunavik",
                                             2407,        "Quebec",                             "Outaouais",  397193,                              "Quebec-Outaouais",
                                             2402,        "Quebec",                              "Saguenay",  277796,                               "Quebec-Saguenay",
                                             2418,        "Quebec",         "Terres-Cries-de-la-Baie-James",   18131,          "Quebec-Terres-Cries-de-la-Baie-James",
                                              473,  "Saskatchewan",                               "Central",   98566,                          "Saskatchewan-Central",
                                              471,  "Saskatchewan",                             "Far North",   37811,                        "Saskatchewan-Far North",
                                              472,  "Saskatchewan",                                 "North",  196246,                            "Saskatchewan-North",
                                              475,  "Saskatchewan",                                "Regina",  304261,                           "Saskatchewan-Regina",
                                              474,  "Saskatchewan",                             "Saskatoon",  380403,                        "Saskatchewan-Saskatoon",
                                              476,  "Saskatchewan",                                 "South",  157175,                            "Saskatchewan-South",
                                             6001,         "Yukon",                                 "Yukon",   40854,                                   "Yukon-Yukon",
                                               NA,        "Quebec",                    "Ensemble du Québec", 8484965,                     "Quebec-Ensemble du Québec"
                                          )
#' population des groupe d'age du Québec
#' @export
#  source: diviser le nombre de cas par le nombre de cas par million dans le fichier de inspq
#"0 à 9 ans"   "10 à 19 ans" "20 à 29 ans" "30 à 39 ans" "40 à 49 ans" "50 à 59 ans" "60 à 69 ans" "70 à 79 ans" "80 à 89 ans" "90 ans et +"
populations_age <- tribble(
  ~groupe_age, ~pop,
  "0 à 9 ans",          	893977,
  "10 à 19 ans",        	878347,
  "20 à 29 ans",        	1056242,
  "30 à 39 ans",        	1115906,
  "40 à 49 ans",        	1100826,
  "50 à 59 ans",        	1182044,
  "60 à 69 ans",        	1147664,
  "70 à 79 ans",        	753700,
  "80 à 89 ans",        	327675,
  "90 ans et +",   	82670,
  "Total" ,  8390499    # tiré de prov_pop
)

#' population des groupe d'age de Montréal
#' @export
# source diviser les cas par le nombre de cas par 100k dans le tableau de santé pulique montréal
populations_age_montreal <- tribble(
  ~groupe_age, ~pop,
  "0-4 ans",	109848,
  "5-9 ans",	107568,
  "10-19 ans",	198906,
  "20-29 ans",	325589,
  "30-39 ans",	328209,
  "40-49 ans",	277589,
  "50-59 ans",	256500,
  "60-69 ans",	216332,
  "70-79 ans",	144506,
  "80 ans et +",	100591
)

#' population des RLS du Québec
#' @export
#source population rls : feuille google de claude
rls_population <- tibble::tribble(
  ~RLS, ~Population,
  "0111 - RLS de Kamouraska",       20780,
  "0112 - RLS de Rivière-du-Loup",       34800,
  "0113 - RLS de Témiscouata",       19117,
  "0114 - RLS des Basques",        8529,
  "0115 - RLS de Rimouski",       57630,
  "0116 - RLS de La Mitis",       17978,
  "0117 - RLS de Matane",       20726,
  "0118 - RLS de La Matapédia",       17514,
  "0211 - RLS du Domaine-du-Roy",       31078,
  "0212 - RLS de Maria-Chapdelaine",       25064,
  "0213 - RLS de Lac-Saint-Jean-Est",       52298,
  "0214 - RLS de Jonquière",       67417,
  "0215 - RLS de Chicoutimi",       79201,
  "0216 - RLS de La Baie",       22574,
  "0311 - RLS de Portneuf",       54895,
  "0312 - RLS de Québec-Sud",      321016,
  "0313 - RLS de Québec-Nord",      351429,
  "0314 - RLS de Charlevoix",       28119,
  "0411 - RLS du Haut-Saint-Maurice",       15020,
  "0412 - RLS de la Vallée de la Batiscan",       25562,
  "0413 - RLS de Maskinongé",       22961,
  "0414 - RLS du Centre-de-la-Mauricie",       64641,
  "0415 - RLS de Trois-Rivières",      143422,
  "0416 - RLS de Bécancour - Nicolet-Yamaska",       44619,
  "0417 - RLS de Drummond",      107872,
  "0418 - RLS d'Arthabaska - de l'Érable",       98244,
  "0511 - RLS de la Pommeraie",       56125,
  "0512 - RLS de la Haute-Yamaska",      105861,
  "0513 - RLS de Memphrémagog",       52514,
  "0514 - RLS de Coaticook",       18741,
  "0515 - RLS de Sherbrooke",      170075,
  "0516 - RLS de Val Saint-François",       31490,
  "0517 - RLS d'Asbestos",       14257,
  "0518 - RLS du Haut-Saint-François",       22749,
  "0519 - RLS du Granit",       21351,
  "0611 - RLS de Pierrefonds - Lac Saint-Louis",      224596,
  "0612 - RLS de Dorval - Lachine - Lasalle",      149522,
  "0621 - RLS de Côte-Saint-Luc - NDG - Montréal-Ouest",      131424,
  "0622 - RLS de Côte-des-Neiges - Métro - Parc-Extension",      245703,
  "0631 - RLS de Verdun - Côte St-Paul - St-Henri - Pointe-St-Charles",      166225,
  "0632 - RLS des Faubourgs - Plateau-Mont-Royal - St-Louis-du-Parc",      161317,
  "0641 - RLS du Nord de l'Île - Saint-Laurent",      161894,
  "0642 - RLS d'Ahuntsic - Montréal-Nord",      172517,
  "0643 - RLS de la Petite Patrie - Villeray",      115485,
  "0651 - RLS de Saint-Léonard - Saint-Michel",      139162,
  "0652 - RLS de Rivière-des-Prairies - Anjou - Montréal-Est",      208717,
  "0653 - RLS de Hochelaga - Mercier-Ouest - Rosemont",      189095,
  "0711 - RLS du Pontiac",       20152,
  "0712 - RLS de la Vallée-de-la-Gatineau",       20552,
  "0713 - RLS des Collines-de-l'Outaouais",       38891,
  "0714 - RLS de Grande-Rivière - Hull - Gatineau",      264517,
  "0715 - RLS de la Vallée-de-la-Lièvre et de la Petite Nation",       56920,
  "0811 - RLS de l'Abitibi-Ouest",       20528,
  "0812 - RLS de l'Abitibi",       24729,
  "0813 - RLS de Rouyn-Noranda",       43180,
  "0814 - RLS de la Vallée-de-l'Or",       43551,
  "0815 - RLS du Témiscaming",       15628,
  "0911 - RLS de Caniapiscau",        3230,
  "0912 - RLS de la Haute-Côte-Nord - Manicouagan",       40494,
  "0913 - RLS de Port-Cartier",        7314,
  "0914 - RLS de Sept-Îles",       27344,
  "0915 - RLS de la Minganie",        6428,
  "0916 - RLS de la Basse-Côte-Nord",        4582,
  "0917 - RLS de Kawawachikamach",         641,
  "1001 - Nord-du-Québec",       13558,
  "1111 - RLS de la Baie-des-Chaleurs",       32176,
  "1112 - RLS de la Haute-Gaspésie",       10582,
  "1113 - RLS de La Côte-de-Gaspé",       18753,
  "1114 - RLS du Rocher-Percé",       15881,
  "1121 - RLS des Îles-de-la-Madeleine",       12606,
  "1211 - RLS Alphonse-Desjardins",      258118,
  "1212 - RLS de la région de Thetford",       42500,
  "1213 - RLS de Beauce",       73173,
  "1214 - RLS des Etchemins",       16426,
  "1215 - RLS de Montmagny-L'Islet",       40092,
  "1311 - RLS de Laval",      442745,
  "1411 - RLS de Lanaudière-Nord",      223099,
  "1412 - RLS de Lanaudière-Sud",      296993,
  "1511 - RLS d'Antoine-Labelle",       35580,
  "1512 - RLS des Laurentides",       48016,
  "1513 - RLS des Pays-d'en-Haut",       44362,
  "1514 - RLS d'Argenteuil",       33422,
  "1515 - RLS de Deux-Montagnes - Mirabel-Sud",      124641,
  "1516 - RLS de la Rivière-du-Nord - Mirabel-Nord",      177517,
  "1517 - RLS de Thérèse-De Blainville",      163430,
  "1611 - RLS de Champlain",      225442,
  "1612 - RLS du Haut-Richelieu - Rouville",      195297,
  "1621 - RLS Pierre-Boucher",      262440,
  "1622 - RLS de Richelieu-Yamaska",      220957,
  "1623 - RLS Pierre-De Saurel",       51371,
  "1631 - RLS de Vaudreuil-Soulanges",      160002,
  "1632 - RLS du Suroît",       60523,
  "1633 - RLS du Haut-Saint-Laurent",       24346,
  "1634 - RLS de Jardins-Roussillon",      232373,
  "1701 - Nunavik",       14260,
  "1801 - Terres-Cries-de-la-Baie-James",       18385
)



